version: '3'
services:
  mysql_db:
    image: mysql:latest
    restart: always
    networks:
        - app_tier
    volumes:
        - ./mysql/db:/var/lib/mysql
        - ./mysql/sql:/sql
    ports:
        - "3306:3306"
    cap_add:
        - SYS_NICE
    environment:
        - MYSQL_DATABASE=app
        - MYSQL_USER=user
        - MYSQL_PASSWORD=1234
        - MYSQL_ROOT_PASSWORD=1234

  websocket:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: websocket
    links:
        - mysql_db:mysql_db
    depends_on:
        - mysql_db
    networks:
        - app_tier
    volumes:
       - .:/app      
    tty: true


networks:  # 네트워크 이름 
  app_tier:
    driver: bridge  # 컨테이너를 bridge로 연결